<?php
/**
 * @file
 * Drupal Front End Developer provides an easy way for theme developers see exactly what viewport resolution they are currently viewing.
 *
 */

/**
 * Implements hook_init()
 */
function dfed_init() {
  if (!path_is_admin(current_path())) {
    drupal_add_js(drupal_get_path('module', 'dfed') . '/js/dfed.js');
    drupal_add_css(drupal_get_path('module', 'dfed') . '/css/dfed.css');
  }
}